service: datacompress

useDotenv: true

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-python-requirements
provider:
    name: aws
    runtime: python3.9
    region: us-east-1
    tags:
        PROYECT: DATA-COMPRESS

package:
    patterns:
        - '!node_modules/**'
        - '!env/**'

functions:
    read-and-compress:
        handler: lambdas/read-and-compress/handler.handler
        description: Compress file stored in S3 buckets
        memorySize: 10240
        timeout: 900
        environment:
            DB_HOST: 'datacompress.c7s82rautvg8.us-east-1.rds.amazonaws.com'
            DB_USERNAME: 'admin'
            DB_PASSWORD: '8fwauRijuo8vTJpYlcqb'
            DB_DATABASE: 'datacompress'
            S3_URL: 'https://after.datacompression.click/'
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
        vpc:
            subnetIds:
                - 'subnet-07d11a6f1648decfa'
                - 'subnet-0501a15d691993d19'
                - 'subnet-015eb033be16f968f'
            securityGroupIds:
                - 'sg-056b5faca088fae6c'
    delete-original-archives:
        handler: lambdas/delete-original-archives/handler.handler
        description: Delete original archives
        memorySize: 128
        timeout: 180
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
    authorizer-google:
        handler: lambdas/authorizer-google/handler.handler
        description: Google Cognito Authorizer
        memorySize: 128
        timeout: 180
        environment:
            IDENTITY_POOL_ID: 'us-east-1:d8b354dc-890e-449a-aa63-3fb78ecaee88'
    pre-signed-url:
        handler: lambdas/pre-signed-url/handler.handler
        description: Pre Signed URL & Store User If Not Exist
        memorySize: 128
        timeout: 180
        environment:
            DB_HOST: 'datacompress.c7s82rautvg8.us-east-1.rds.amazonaws.com'
            DB_USERNAME: 'admin'
            DB_PASSWORD: '8fwauRijuo8vTJpYlcqb'
            DB_DATABASE: 'datacompress'
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
        events:
            - http:
                  path: pre-signed-url
                  method: post
                  cors: true
        vpc:
            subnetIds:
                - 'subnet-07d11a6f1648decfa'
                - 'subnet-0501a15d691993d19'
                - 'subnet-015eb033be16f968f'
            securityGroupIds:
                - 'sg-056b5faca088fae6c'
    get-compressed-files:
        handler: lambdas/get-compressed-files/handler.handler
        description: Get Compressed files by email
        memorySize: 128
        timeout: 180
        environment:
            DB_HOST: 'datacompress.c7s82rautvg8.us-east-1.rds.amazonaws.com'
            DB_USERNAME: 'admin'
            DB_PASSWORD: '8fwauRijuo8vTJpYlcqb'
            DB_DATABASE: 'datacompress'
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
        events:
            - http:
                  path: get-compressed-files
                  method: post
                  cors: true
                  authorizer:
                      name: authorizer-google
                      resultTtlInSeconds: 0
        vpc:
            subnetIds:
                - 'subnet-07d11a6f1648decfa'
                - 'subnet-0501a15d691993d19'
                - 'subnet-015eb033be16f968f'
            securityGroupIds:
                - 'sg-056b5faca088fae6c'
    delete-final-archive-s3-and-update-db:
        handler: lambdas/delete-final-archive-s3-and-update-db/handler.handler
        description: Delete Final Archive From S3 And Update DB
        memorySize: 128
        timeout: 180
        environment:
            DB_HOST: 'datacompress.c7s82rautvg8.us-east-1.rds.amazonaws.com'
            DB_USERNAME: 'admin'
            DB_PASSWORD: '8fwauRijuo8vTJpYlcqb'
            DB_DATABASE: 'datacompress'
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
        events:
            - http:
                  path: delete-final-archive
                  method: post
                  cors: true
                  authorizer:
                      name: authorizer-google
                      resultTtlInSeconds: 0
        vpc:
            subnetIds:
                - 'subnet-07d11a6f1648decfa'
                - 'subnet-0501a15d691993d19'
                - 'subnet-015eb033be16f968f'
            securityGroupIds:
                - 'sg-056b5faca088fae6c'
