service: datacompress

variablesResolutionMode: 20210326
useDotenv: true

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-python-requirements
provider:
    name: aws
    runtime: python3.8
    region: us-east-1
    lambdaHashingVersion: 20201221
    tags:
        PROYECT: DATA-COMPRESS

package:
    patterns:
        - '!node_modules/**'
        - '!env/**'

functions:
    read-and-compress:
        handler: lambdas/read-and-compress/handler.handler
        description: Compress file stored in S3 buckets
        memorySize: 128
        timeout: 180
        environment:
            DB_HOST: 'datacompress.c7s82rautvg8.us-east-1.rds.amazonaws.com'
            DB_USERNAME: 'admin'
            DB_PASSWORD: '8fwauRijuo8vTJpYlcqb'
            DB_DATABASE: 'datacompress'
            S3_URL: 'https://after.datacompression.click/'
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
        vpc:
            subnetIds:
                - 'subnet-07d11a6f1648decfa'
                - 'subnet-0501a15d691993d19'
                - 'subnet-015eb033be16f968f'
            securityGroupIds:
                - 'sg-056b5faca088fae6c'
    delete-original-archives:
        handler: lambdas/delete-original-archives/handler.handler
        description: Delete original archives
        memorySize: 128
        timeout: 180
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
    authenticate-google:
        handler: lambdas/authenticate-google/handler.handler
        description: Google Cognito Authentication
        memorySize: 128
        timeout: 180
        environment:
            IDENTITY_POOL_ID: 'us-east-1:d8b354dc-890e-449a-aa63-3fb78ecaee88'
        events:
            - http:
                  path: auth
                  method: get
                  cors: true
    pre-signed-url:
        handler: lambdas/pre-signed-url/handler.handler
        description: Pre Signed URL & Store User If Not Exist
        memorySize: 128
        timeout: 180
        environment:
            DB_HOST: 'datacompress.c7s82rautvg8.us-east-1.rds.amazonaws.com'
            DB_USERNAME: 'admin'
            DB_PASSWORD: '8fwauRijuo8vTJpYlcqb'
            DB_DATABASE: 'datacompress'
        role: arn:aws:iam::121116659934:role/LambdaS3CloudWatchFullAccess
        events:
            - http:
                  path: pre-signed-url
                  method: post
                  cors: true
        vpc:
            subnetIds:
                - 'subnet-07d11a6f1648decfa'
                - 'subnet-0501a15d691993d19'
                - 'subnet-015eb033be16f968f'
            securityGroupIds:
                - 'sg-056b5faca088fae6c'
